services:
  #  prometheus:
  #    image: prom/prometheus:latest
  #    ports:
  #      - "9090:9090"
  #    volumes:
  #      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #    command:
  #      - '--config.file=/etc/prometheus/prometheus.yml'
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: